#!/bin/bash
# Copyright (c) 2026, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

set -eo pipefail

source /app/utils.sh

if [ "$AUTH_MODE" = "oauth2" ]; then
  export TRADING_PARTNER_PARTICIPANT_ADMIN_TOKEN=$(get_admin_token $AUTH_TRADING_PARTNER_VALIDATOR_CLIENT_SECRET $AUTH_TRADING_PARTNER_VALIDATOR_CLIENT_ID $AUTH_TRADING_PARTNER_TOKEN_URL)
  export TRADING_PARTNER_PARTY=$(get_user_party "$TRADING_PARTNER_PARTICIPANT_ADMIN_TOKEN" $AUTH_TRADING_PARTNER_VALIDATOR_USER_ID "canton:1${PARTICIPANT_JSON_API_PORT_SUFFIX}")
  export TRADING_PARTNER_WALLET_ADMIN_TOKEN=$(get_user_token $AUTH_TRADING_PARTNER_WALLET_ADMIN_USER_NAME $AUTH_TRADING_PARTNER_WALLET_ADMIN_USER_PASSWORD $AUTH_TRADING_PARTNER_AUTO_CONFIG_CLIENT_ID $AUTH_TRADING_PARTNER_TOKEN_URL)

  if [ "$DO_INIT" == "true" ] && [ ! -f /tmp/trading-partner-init-user-cleanup ]; then
    update_user "$TRADING_PARTNER_PARTICIPANT_ADMIN_TOKEN" $AUTH_TRADING_PARTNER_WALLET_ADMIN_USER_ID $AUTH_TRADING_PARTNER_WALLET_ADMIN_USER_NAME $TRADING_PARTNER_PARTY "canton:1${PARTICIPANT_JSON_API_PORT_SUFFIX}"
    update_user "$TRADING_PARTNER_PARTICIPANT_ADMIN_TOKEN" $AUTH_TRADING_PARTNER_VALIDATOR_USER_ID $AUTH_TRADING_PARTNER_VALIDATOR_USER_NAME $TRADING_PARTNER_PARTY "canton:1${PARTICIPANT_JSON_API_PORT_SUFFIX}"

    delete_user "$TRADING_PARTNER_PARTICIPANT_ADMIN_TOKEN" participant_admin "canton:1${PARTICIPANT_JSON_API_PORT_SUFFIX}"
    touch /tmp/trading-partner-init-user-cleanup
  fi

else
  export TRADING_PARTNER_PARTICIPANT_ADMIN_TOKEN=$(generate_jwt "$AUTH_TRADING_PARTNER_VALIDATOR_USER_NAME" "$AUTH_TRADING_PARTNER_AUDIENCE")
  export TRADING_PARTNER_PARTY=$(get_user_party "$TRADING_PARTNER_PARTICIPANT_ADMIN_TOKEN" $AUTH_TRADING_PARTNER_VALIDATOR_USER_NAME "canton:1${PARTICIPANT_JSON_API_PORT_SUFFIX}")
  export TRADING_PARTNER_WALLET_ADMIN_TOKEN=$(generate_jwt "$AUTH_TRADING_PARTNER_WALLET_ADMIN_USER_NAME" "$AUTH_TRADING_PARTNER_AUDIENCE")

  if [ "$DO_INIT" == "true" ] && [ ! -f /tmp/trading-partner-init-user-cleanup ]; then
    delete_user "$TRADING_PARTNER_PARTICIPANT_ADMIN_TOKEN" participant_admin "canton:1${PARTICIPANT_JSON_API_PORT_SUFFIX}"
    touch /tmp/trading-partner-init-user-cleanup
  fi
fi
