canton.validator-apps.tp-validator_backend {
  participant-client.ledger-api.auth-config = {
    type = "self-signed"
    user = ${AUTH_TRADING_PARTNER_VALIDATOR_USER_NAME}
    audience = ${AUTH_TRADING_PARTNER_AUDIENCE}
    secret = "unsafe"
  }

  auth = {
    algorithm = "hs-256-unsafe"
    audience = ${AUTH_TRADING_PARTNER_AUDIENCE}
    secret = "unsafe"
  }

  ledger-api-user = ${AUTH_TRADING_PARTNER_VALIDATOR_USER_NAME}
  validator-wallet-users.0 = ${AUTH_TRADING_PARTNER_WALLET_ADMIN_USER_NAME}

}
