#!/bin/bash
# Requests a partner API key from the canton-exchange-backend for use by the trading partner.
#
# This script:
#   1. Reads trading-partner-config.json for party ID and auth config
#   2. Logs into the exchange backend as admin
#   3. Issues a new partner API key via POST /admin/partner-api-keys
#   4. Writes the key to partner-api-key.json
#   5. Writes a trade-request-config.json with default trade request parameters
#
# Prerequisites:
#   - setup-trading-partner/.env configured (BACKEND_ADMIN_USERNAME, BACKEND_ADMIN_PASSWORD)
#   - setup-exchange/.env configured (BACKEND_URL)
#   - trading-partner-config.json exists (run 01-setup-trading-partner.sh first)
#   - canton-exchange-backend running at BACKEND_URL
#
# Usage:
#   ./02-request-partner-api-key.sh

set -eo pipefail

##############################################################################
# Configuration
##############################################################################

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SETUP_EXCHANGE_DIR="$SCRIPT_DIR/../setup-exchange"
INTERNAL_PARTIES_DIR="$SCRIPT_DIR/../setup-internal-parties"

# Load trading-partner config
if [ ! -f "$SCRIPT_DIR/.env" ]; then
  echo "[partner-api-key] ERROR: $SCRIPT_DIR/.env not found. Copy .env.example to .env first." >&2
  exit 1
fi
if [ ! -f "$SETUP_EXCHANGE_DIR/.env" ]; then
  echo "[partner-api-key] ERROR: $SETUP_EXCHANGE_DIR/.env not found. Run setup-exchange scripts first." >&2
  exit 1
fi
# shellcheck disable=SC1091
source "$SCRIPT_DIR/.env"
# shellcheck disable=SC1091
source "$SETUP_EXCHANGE_DIR/.env"

# Load trading-partner-config.json (generated by 01-setup-trading-partner.sh)
TP_CONFIG="$SCRIPT_DIR/trading-partner-config.json"
if [ ! -f "$TP_CONFIG" ]; then
  echo "[partner-api-key] ERROR: trading-partner-config.json not found. Run 01-setup-trading-partner.sh first." >&2
  exit 1
fi

TRADING_PARTNER_PARTY=$(jq -r '.tradingPartnerParty' "$TP_CONFIG")

# Backend config (from setup-exchange/.env)
BACKEND_URL="${BACKEND_URL:-http://localhost:3003}"
BACKEND_ADMIN_USERNAME="${BACKEND_ADMIN_USERNAME:-superadmin}"

if [ -z "$BACKEND_ADMIN_PASSWORD" ]; then
  echo "[partner-api-key] ERROR: BACKEND_ADMIN_PASSWORD not set. Add it to $SETUP_EXCHANGE_DIR/.env." >&2
  exit 1
fi

OUTPUT_FILE="$SCRIPT_DIR/partner-api-key.json"
CONFIG_FILE="$SCRIPT_DIR/trade-request-config.json"

##############################################################################
# Helper Functions
##############################################################################

log() { echo "[partner-api-key] $*"; }
log_error() { echo "[partner-api-key] ERROR: $*" >&2; }

##############################################################################
# Main
##############################################################################

log "=========================================="
log "Request Partner API Key"
log "=========================================="
log "  Backend:         $BACKEND_URL"
log "  Trading Partner: ${TRADING_PARTNER_PARTY:0:60}..."
log ""

##############################################################################
# Step 1: Admin login
##############################################################################

log "Step 1: Logging in as admin ($BACKEND_ADMIN_USERNAME)..."

LOGIN_RESULT=$(curl -s -w "\n%{http_code}" "$BACKEND_URL/admin/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"username\": \"$BACKEND_ADMIN_USERNAME\", \"password\": \"$BACKEND_ADMIN_PASSWORD\"}")

LOGIN_HTTP=$(echo "$LOGIN_RESULT" | tail -n1 | tr -d '\r')
LOGIN_BODY=$(echo "$LOGIN_RESULT" | sed '$d')

if [ "$LOGIN_HTTP" -ne "200" ] && [ "$LOGIN_HTTP" -ne "201" ]; then
  log_error "Admin login failed with HTTP $LOGIN_HTTP"
  log_error "Response: $LOGIN_BODY"
  exit 1
fi

ADMIN_TOKEN=$(echo "$LOGIN_BODY" | jq -r '.data.accessToken // .accessToken // empty')
ADMIN_ID=$(echo "$LOGIN_BODY" | jq -r '.data.admin.id // empty')

if [ -z "$ADMIN_TOKEN" ]; then
  log_error "Failed to extract admin access token from login response"
  exit 1
fi
log "  Admin login successful (ID: $ADMIN_ID)"

##############################################################################
# Step 2: Issue partner API key
##############################################################################

# Use the party hint (before ::) as a human-readable name suffix
TP_HINT="${TRADING_PARTNER_PARTY%%::*}"
KEY_NAME="Trading Partner - $TP_HINT"

log ""
log "Step 2: Issuing partner API key ('$KEY_NAME')..."

KEY_RESULT=$(curl -s -w "\n%{http_code}" "$BACKEND_URL/admin/partner-api-keys" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ADMIN_TOKEN" \
  -d "$(jq -n \
    --arg adminId "$ADMIN_ID" \
    --arg name "$KEY_NAME" \
    '{adminId: $adminId, name: $name}')")

KEY_HTTP=$(echo "$KEY_RESULT" | tail -n1 | tr -d '\r')
KEY_BODY=$(echo "$KEY_RESULT" | sed '$d')

if [ "$KEY_HTTP" -ne "200" ] && [ "$KEY_HTTP" -ne "201" ]; then
  log_error "Partner API key creation failed with HTTP $KEY_HTTP"
  log_error "Response: $KEY_BODY"
  exit 1
fi

PARTNER_API_KEY=$(echo "$KEY_BODY" | jq -r '.data.rawKey // .rawKey // empty')
KEY_ID=$(echo "$KEY_BODY" | jq -r '.data.id // .id // empty')
KEY_PREFIX=$(echo "$KEY_BODY" | jq -r '.data.prefix // .prefix // empty')

if [ -z "$PARTNER_API_KEY" ]; then
  log_error "Failed to extract partner API key from response"
  log_error "Response: $(echo "$KEY_BODY" | head -c 300)"
  exit 1
fi
log "  Key issued: ${PARTNER_API_KEY:0:12}... (ID: $KEY_ID)"

##############################################################################
# Step 3: Write partner-api-key.json
##############################################################################

log ""
log "Step 3: Writing $OUTPUT_FILE..."

jq -n \
  --arg generatedAt "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --arg keyId "$KEY_ID" \
  --arg keyPrefix "$KEY_PREFIX" \
  --arg keyName "$KEY_NAME" \
  --arg rawKey "$PARTNER_API_KEY" \
  --arg backendUrl "$BACKEND_URL" \
  --arg tradingPartnerParty "$TRADING_PARTNER_PARTY" \
  '{
    generatedAt: $generatedAt,
    backendUrl: $backendUrl,
    tradingPartnerParty: $tradingPartnerParty,
    partnerApiKey: {
      id: $keyId,
      prefix: $keyPrefix,
      name: $keyName,
      rawKey: $rawKey
    }
  }' > "$OUTPUT_FILE"

log "  Written: $OUTPUT_FILE"

##############################################################################
# Step 4: Write trade-request-config.json
##############################################################################

log ""
log "Step 4: Writing $CONFIG_FILE..."

# Read first trader from internal-parties.json if available
INTERNAL_PARTIES_FILE="$INTERNAL_PARTIES_DIR/internal-parties.json"
TRADER_PARTY_ID=""
TRADER_USER_ID=""
if [ -f "$INTERNAL_PARTIES_FILE" ]; then
  TRADER_PARTY_ID=$(jq -r '.parties[0].partyId // empty' "$INTERNAL_PARTIES_FILE")
  TRADER_USER_ID=$(jq -r '.parties[0].userId // empty' "$INTERNAL_PARTIES_FILE")
  if [ -n "$TRADER_PARTY_ID" ]; then
    log "  Detected trader: $TRADER_USER_ID"
  fi
fi

jq -n \
  --arg generatedAt "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --arg partnerApiKey "$PARTNER_API_KEY" \
  --arg backendUrl "$BACKEND_URL" \
  --arg tradingPartnerParty "$TRADING_PARTNER_PARTY" \
  --arg traderPartyId "$TRADER_PARTY_ID" \
  --arg traderUserId "$TRADER_USER_ID" \
  '{
    generatedAt: $generatedAt,
    backendUrl: $backendUrl,
    partnerApiKey: $partnerApiKey,
    tradingPartnerParty: $tradingPartnerParty,
    traderPartyId: $traderPartyId,
    traderUserId: $traderUserId,
    tradeRequest: {
      inputAmount: "10",
      inputTokenType: "Amulet",
      outputTokenType: "CBTC"
    }
  }' > "$CONFIG_FILE"

log "  Written: $CONFIG_FILE"

##############################################################################
# Done
##############################################################################

log ""
log "=========================================="
log "Partner API Key Ready!"
log "=========================================="
log ""
log "Summary:"
log "  Key ID:          $KEY_ID"
log "  Key prefix:      ${PARTNER_API_KEY:0:12}..."
log "  Output:          $OUTPUT_FILE"
log "  Trade config:    $CONFIG_FILE"
log ""
log "Next steps:"
log "  1. Ensure a trader has Amulet holdings:"
log "     cd ../setup-internal-parties && ./04-faucet-amulet.sh"
log "  2. Run the trade request test:"
log "     ./test-trade-request.sh"
