canton.participants.trading-partner {
  ledger-api{
    auth-services = [{
      type = unsafe-jwt-hmac-256
      target-audience = ${AUTH_TRADING_PARTNER_AUDIENCE}
      secret = "unsafe"
    }]

    user-management-service.additional-admin-user-id = ${AUTH_TRADING_PARTNER_VALIDATOR_USER_NAME}
  }
}
